# Generated by Django 3.1b1 on 2020-12-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
