# Generated by Django 3.1b1 on 2020-09-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_issue',
            field=models.BooleanField(default='False'),
        ),
    ]
