# Generated by Django 3.1b1 on 2020-12-04 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_poll_is_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='choice1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='choice2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='choice3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='choice4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('poll', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'Comment must be greater than 3 characters')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.poll')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_polls', through='home.Fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
