# Generated by Django 3.1b1 on 2020-12-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201204_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='Required_City',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Required_Minimum_Age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Required_Sex',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
